name = "AtomicAndPhysicalConstants"
uuid = "5c0d271c-5419-4163-b387-496237733d8b"
authors = ["David Sagan <david.sagan@cornell.edu> and contributors"]
version = "0.8.0"

[deps]

[compat]
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
